name: build and test

on:
  push:
    branches:
      - 'unit_tests'
      - 'master'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main # latest version of https://github.com/actions/checkout , (alternatively use: actions/checkout@v3.3.0)
      - name: cmake files
        run: cmake tests/CMakeLists.txt -B build
      - name: Build
        run: cmake --build build --config Debug
      - name: explore folder # show build artifacts in folder
        run: ls build
      - name: Run
        run: ./build/IEEE754_binary_encoder
